<a href="https://colab.research.google.com/github/Syamefx/2026-assigment-case-study/blob/main/Data_Pro_assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Question 1.**

In [58]:
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv('/content/employee (1).csv')

In [60]:
df.shape

(9, 7)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               9 non-null      object
 1   age                7 non-null      float64
 2   income             7 non-null      float64
 3   gender             7 non-null      object
 4   department         9 non-null      object
 5   grade              9 non-null      object
 6   performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

In [62]:
df.head()

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

# **Question 2.**

# Setting the column "name" as the index.

In [63]:
df.set_index('name', inplace=True)

In [64]:
df.head((5))

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
S Kumar         NaN  16000.0      F     Finance    G0                520
Jack Morgan    32.0  35000.0      M     Finance    G2                674
Ying Chin      45.0  65000.0      F       Sales    G3                556
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

# **Question 3.**

# Display of employee who has more than 700 performance score

In [65]:
emp_700 = df[df['performance_score'] > 700]
print("Employees with a performance score over 700:")
display(emp_700)

Employees with a performance score over 700:

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
Josh Wills     54.0  52000.0      F     Finance    G3                901
Leo Duck       23.0  98000.0      M       Sales    G4                709

# **Question 4.**

# Displaying of employee who has more than 500 and less than 700 performance score

In [66]:
mid_per = df.query('500 < performance_score < 700')

In [67]:
print("Employees in the 500-700 range:",mid_per)

Employees in the 500-700 range:                 age   income gender department grade  performance_score
name
S Kumar         NaN  16000.0      F    Finance    G0                520
Jack Morgan    32.0  35000.0      M    Finance    G2                674
Ying Chin      45.0  65000.0      F      Sales    G3                556
Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649

# **Question 5.**

# Checked and handled missing values in the dataset

In [68]:
print("Missing values before :\n", df.isna().sum())
for col in ['age', 'income']:
    if df[col].isna().sum() > 0:
        med_val = df[col].median()
        df[col].fillna(med_val, inplace=True)
# Fixing missing values
most_common_gender = df['gender'].mode()[0]
df['gender'].fillna(most_common_gender, inplace=True)

print("\nMissing values after applying fixes:\n", df.isna().sum())

Missing values before :
 age                  2
income               2
gender               2
department           0
grade                0
performance_score    0
dtype: int64

Missing values after applying fixes:
 age                  0
income               0
gender               0
department           0
grade                0
performance_score    0
dtype: int64

/tmp/ipykernel_10312/581831458.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(med_val, inplace=True)
/tmp/ipykernel_10312/581831458.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(most_common_gender, inplace=True)

# **Question 6.**

#Checking the outliers and handle outliers in performance score using Percentiles

In [69]:
# finding out the upper and lower percentile limits
lower_lim = df['performance_score'].quantile(0.05)
upper_lim = df['performance_score'].quantile(0.95)

print(f"Capping scores below {lower_lim} and above {upper_lim}")

# capping the outliers directly
df['performance_score'] = np.clip(df['performance_score'], lower_lim, upper_lim)
print(df['performance_score'])
print("-"*200)
print(df)

Capping scores below 239.8 and above 829.8
name
Allen Smith      723.0
S Kumar          520.0
Jack Morgan      674.0
Ying Chin        556.0
Dheeraj Patel    711.0
Satyam Sharma    649.0
James Authur     239.8
Josh Wills       829.8
Leo Duck         709.0
Name: performance_score, dtype: float64
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                age   income gender  department grade  performance_score
name
Allen Smith    45.0  52000.0      F  Operations    G3              723.0
S Kumar        45.0  16000.0      F     Finance    G0              520.0
Jack Morgan    32.0  35000.0      M     Finance    G2              674.0
Ying Chin      45.0  65000.0      F       Sales    G3              556.0
Dheeraj Patel  30.0  42000.0      F  Operations    G2              711.0
Satyam Sharma  45.0  62000.0      F       Sales    G3              649.0
James Authur   54.0  52000.0      F  Operations    G3              239.8
Josh Wills     54.0  52000.0      F     Finance    G3              829.8
Leo Duck       23.0  98000.0      M       Sales    G4              709.0

# **Question 7.**

Checking the gender column and doing one hot encoding

In [70]:
df = pd.get_dummies(df, columns=['gender'])
print(df.head())

                age   income  department grade  performance_score  gender_F  \
name
Allen Smith    45.0  52000.0  Operations    G3              723.0      True
S Kumar        45.0  16000.0     Finance    G0              520.0      True
Jack Morgan    32.0  35000.0     Finance    G2              674.0     False
Ying Chin      45.0  65000.0       Sales    G3              556.0      True
Dheeraj Patel  30.0  42000.0  Operations    G2              711.0      True

               gender_M
name
Allen Smith       False
S Kumar           False
Jack Morgan        True
Ying Chin         False
Dheeraj Patel     False